[package]
name = "sqlite3-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bytemuck = { version = "1.14.0", features = ["derive"] }
zerocopy = { version = "0.7.8", features = ["derive"] }
